apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: quizapp
spec:
  scaleTargetRef:
    name: quizapp-java-app
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090
        metricName: http_server_requests_seconds_count
        threshold: "600"
        query: sum(rate(http_server_requests_seconds_count{namespace="quizapp", pod=~"quizapp-java-app.*"}[1m]))
